A6: Chess Board
sudarson-25/Training2024 pull request #14
Opened 2024-11-25 05:35 UTC by sudarson-25

PR created for review

2024-11-25 08:49 UTC, dineshN52 requested changes

2024-11-25 08:49 UTC, dineshN52 commented on Training/Training/Training.c
> +            case 2: for (int j = 0; j < 8; j++) PrintWrite (L"┃  ♟", fp);
Why black pawns don't have a space after its placement while white pawns have? And this also leads to improper placement of characters

2024-11-25 08:49 UTC, dineshN52 commented on Training/Training/Training.c
> +      if (outChar == WEOF && refChar == WEOF) wprintf (ANSI_COLOR_GREEN L"PASSED\n" ANSI_COLOR_RESET);
The above condition in while and inside this if are just negated version of each other, so if while fails, it is obvious the below is passed, so no need to check

2024-11-25 08:49 UTC, dineshN52 commented on Training/Training/Training.c
> +      int matchFlag = 0, charFlag = 0;
What is the purpose of having flags here?

2024-11-25 09:06 UTC, sudarson-25 commented on Training/Training/Training.c
> +            case 2: for (int j = 0; j < 8; j++) PrintWrite (L"┃  ♟", fp);
Black pawn occupies extra space than other unicode characters. So other characters have been adjusted to match the black pawn.

2024-11-25 09:14 UTC, sudarson-25 commented on Training/Training/Training.c
> +      if (outChar == WEOF && refChar == WEOF) wprintf (ANSI_COLOR_GREEN L"PASSED\n" ANSI_COLOR_RESET);
If one file has more characters than the other, and if all the characters of the shorter file is same as the longer file, the while loop would end. The function would print "passed" which is undesirable.

2024-11-26 05:47 UTC, dineshN52 requested changes

2024-11-26 05:47 UTC, dineshN52 commented on Training/Training/Training.c
> +      PrintBox (L"┏", L"┳", L"┓", fp);
Is that printing individual characters necessary here, Try print the whole line here, look for similar corrections in the code

2024-12-19 06:05 UTC, Dakshita-Minocha commented on Training/Training/Training.c
> +         }
Read full file at once, then compare

2024-12-19 06:05 UTC, Dakshita-Minocha commented on Training/Training/unicode_output.txt
> +﻿┏━━━━┳━━━━┳━━━━┳━━━━┳━━━━┳━━━━┳━━━━┳━━━━┓
Don't push output file

2024-12-19 06:05 UTC, Dakshita-Minocha commented on Training/Training/Training.c
> +               fputws (L" ", fp);
Why not use PrintWrite () here?

2025-01-03 09:13 UTC, Dakshita-Minocha approved these changes

2025-01-03 09:13 UTC, closed without merging