Test1.2
sudarson-25/Training2024 pull request #15
Opened 2024-11-27 12:47 UTC by sudarson-25

PR created for review

2024-11-28 05:09 UTC, sanjivtmm commented on Training/Training/testcomplex.c
> +   Complex input[] = { 5,4,6,-5 }, expected[] = { 11,-1,-1,9,50,-1,5,-4 };
You should do the initialization like this:
   Complex input[] = { {5,4},{6,-5} }, expected[] = { {11,-1},{-1,9},{50,-1},{5,-4} };
It clearly shows how many complex numbers are being initialized and what are the real and imaginary parts.

2024-11-28 05:09 UTC, sanjivtmm commented on Training/Training/testcomplex.c
> +   Complex D = OpAdd (input[0], input[1]), E = OpSub (input[0], input[1]),
Readability is not good. Improve it by formatting your code as follows:
   Complex  D = OpAdd (input[0],input[1]),
                   E = OpSub (input[0], input[1]),
                   F = OpMul (input[0], input[1]), G = OpConj (input[0]);

2024-11-28 05:09 UTC, sanjivtmm commented on Training/Training/testcomplex.c
> +   D.real == expected[0].real && D.img == expected[0].img ? printf ("\nADD Passed") : printf ("\nADD Failed");
Use parenthesis to improve readability.
The tertiary operator is better used when it returns a value and can be used in an expression.
A regular if..else statement is better in this case.

2024-11-28 05:09 UTC, sanjivtmm commented on Training/Training/testcomplex.c
> +   printf ("Enter the real part of the first number: ");
Why are you still manually testing the code? This is not very robust. Did you try entering a non-numeric string, or a string of numbers like 1.2 2.4 3.6 4.8?

2024-11-28 05:09 UTC, sanjivtmm commented on Training/Training/testcomplex.c
> +   TestCases ();
Too few automated tests.
It is possible to the function TestCases to take parameters.
Think of how to automatically generate the test cases.
This is a thought for the future.

2024-11-28 08:31 UTC, Dakshita-Minocha commented
Branch is named correctly but PR should always be named with the original name i.e., "Test1" and be provided with a description. 
"Test1: Complex Numbers" in this case.

2024-12-12 04:35 UTC, Dakshita-Minocha requested changes

2024-12-12 04:35 UTC, Dakshita-Minocha commented on Training/Training/complex.c
> +}
Conventionally, we name methods like this (that return only bool) IsEqual (). Compare (a, b) methods return 1, 0, -1 as value based on whether a > b, a = b or a < b.

2024-12-12 04:35 UTC, Dakshita-Minocha commented on Training/Training/testcomplex.c
> +         "\nMOD Passed\n" : "\nMOD Failed\n");
I think the best way for you to indicate a failed test would be to print failed (or passed) only once for continue;
```suggestion
      printf ("Case 1: ");
      if (!Compare (D, H)) { printf("\nADD Failed"); continue; }
     // etc
     printf ("Passed");
```
and so on. This has two advantages: 1. It fails and stop running that particular test the moment it fails (which is desirable) and it tells you exactly where it is failing. There is a thing called "[Fail fast and Fail Loud](https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so)"
2. It declutters and helps the user understand where the problem is occurring in a minimum number of words.

2024-12-12 05:26 UTC, Dakshita-Minocha requested changes

2024-12-12 05:26 UTC, Dakshita-Minocha commented on Training/Training/testcomplex.c
> +         "\nMOD Passed\n" : "\nMOD Failed\n");
```suggestion
      printf (Compare (Op_Add (a, b) , H) ? "\nADD Passed" : "\nADD Failed");
```
This is more intuitive. The cache-ing is not required as the value is only being used once.

2024-12-17 05:44 UTC, Dakshita-Minocha approved these changes

2024-12-17 05:44 UTC, closed without merging