Assignment3
sudarson-25/Training2024 pull request #7
Opened 2024-08-29 05:38 UTC by sudarson-25

2024-08-29 06:19 UTC, RaaneshKumar commented
Handle cases for non-decimal inputs.
<img width="416" alt="image" src="https://github.com/user-attachments/assets/c9b8af36-30d7-4a82-8415-01f388f1fe57">

2024-08-29 07:07 UTC, RaaneshKumar requested changes

2024-08-29 07:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +   printf ("Input (Enter an integer): ");
Ask user inputs in an infinite loop such that we can check the program multiple times in a single run. In your case the program ends for each try.

2024-08-29 07:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +      binRev = (int*)malloc (mCount * sizeof (int));
Can't we just have an array for this process?

2024-08-29 07:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +   }
This part of code is getting repeated multiple times which I think is unnecessary. You can collect all the remainders in a collection and use them further wherever required and the count of the collection will itself do the job of mCount. Try this. Even if this part of code is required for sure in multiple parts of the code move it to a method and call it wherever necessary to avoid repetition of the code.

2024-08-29 07:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +         }
Brackets can be removed for single line statements in if-else conditions.

2024-08-30 07:14 UTC, RaaneshKumar commented
Unassign yourself before assigning others. There should be only one assignee at a time.

2024-08-30 07:43 UTC, RaaneshKumar requested changes

2024-08-30 07:43 UTC, RaaneshKumar commented on Training/Training/main.c
> +int count (int dec, int div) {
Method name must begin with an uppercase letter.

2024-08-30 07:43 UTC, RaaneshKumar commented on Training/Training/main.c
> +      return 8;
Can be written in the same line. Apply wherever possible.

2024-08-30 07:43 UTC, RaaneshKumar commented on Training/Training/main.c
> +            icount = 0;
Can be written in a single line.
place = 0, icount = 0;

2024-08-30 07:43 UTC, RaaneshKumar commented on Training/Training/main.c
> +   int dec1 = dec;
The names for variables dec1 and dec2 can be more meaningful. For example, int dec, dec2, dec1 can be named as n, nTemp, negN respectively which will explain its purpose by just reading.

2024-08-30 07:43 UTC, RaaneshKumar commented on Training/Training/main.c
> +      dec1 /= 16;
Can be written using ternary operators. Will look like this.
hexRev [i] = dec1 % 16 >= 10 ? (dec1 % 16) + 55 : (dec1 % 16) + 48;
Apply wherever possible.

2024-08-30 07:43 UTC, RaaneshKumar commented on Training/Training/main.c
> +   char term;
dec = 0 can be handled in main itself. Otherwise, it will have to run through the whole program to just print the very known output 0.

2024-08-30 07:46 UTC, RaaneshKumar commented
Make sure your commits are in the form "A3: Your message.". This is the format for commits used in Metamation. Stick to it hereafter. Also change the title from "Assignment3" to "A3: Number Conversion Game". Follow this format for titles in the upcoming assignments also.

2024-08-30 12:07 UTC, RaaneshKumar requested changes

2024-08-30 12:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +      }
Brackets can be removed.

2024-08-30 12:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +            ind++;
Can be written in a single line. Will look like
hexNegRev[ind++] = digit >= 10 ? digit + 55 : digit + 48;
Make this change wherever applicable.

2024-08-30 12:07 UTC, RaaneshKumar commented on Training/Training/main.c
> +            }
Brackets can be removed for single line statements. Make this change wherever applicable. Review your code once before pushing.

2024-09-02 07:49 UTC, RaaneshKumar commented
Don't make changes and commit when it is assigned to someone else. If you need to make a change, please assign it to yourself and then do your change.

2024-09-02 07:54 UTC, RaaneshKumar requested changes

2024-09-02 07:54 UTC, RaaneshKumar commented on Training/Training/main.c
> +            printf ("\n\n");
Not necessary. If dec = 0, you can simply print the answer as a string itself.

2024-09-03 13:03 UTC, Dakshita-Minocha commented on Training/Training/Training.vcxproj
> -    <ClCompile Include="Training.c" />
You don't need to rename the file everytime. Trainng.c is okay, unless you add more files and need to give context.

2024-09-03 13:03 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +int Count (int dec, int div) {
DigitCount may be a more appropriate name.

2024-09-03 13:03 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +   //Counting the number of digits in binary representation
You do not need to add comments like this if you document (comment) your functions properly

2024-09-03 13:03 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +int mCount;
If the only reason you have declared mCount as global is that you don't want to declare it again, it is not required. You should declare it within the functions. Otherwise please let me know the reason.

2024-09-03 13:03 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +   while (dec > 0) {
Count calculates log2 here. You can use log2 () from Math.h. Similarly use log10 where required.

2024-09-03 13:03 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +   } else { //Performing two's compliment
Also, it's nice that you've tried to implement 2's complement logic manually, but there is an easier way to do this. Explore bit shift operators as an alternative.

2024-09-06 03:57 UTC, Dakshita-Minocha reviewed
Please write a test with edge cases and show if your code passes / fails these tests.

2024-09-10 10:09 UTC, Dakshita-Minocha approved these changes

2024-09-10 10:09 UTC, Dakshita-Minocha commented on Training/Training/main.c
>  /// Function that counts the number of bits the binary/hex representation will occupy
```suggestion
/// Returns number of bits required to represent number in multiples of 8.
```

2024-09-10 10:09 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +int DigitsCount (int dec, int div) {
dev and div don't indicate what they are. num may be a better alternative (for dec), base for div

2024-09-10 10:09 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +      if (scanf_s ("%d%c", &dec, &term, 1) != 2 || term != '\n') {
[scanf should be preferred for formatted input](https://c-faq.com/stdio/scanfprobs.html). For inputs from stdin, it is better to use fgets or other methods that read the whole line at once.

2024-09-10 10:09 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +      } else if (dec < INT_MIN || dec > INT_MAX)
This line of code is never hit 
![image](https://github.com/user-attachments/assets/9f7dd27a-dc1c-4500-b774-305d9d9f0b89)

2024-09-10 10:09 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +      else
```suggestion
      if else
printf (flag == digits ? ANSI_COLOR_GREEN"Passed"ANSI_COLOR_RESET"\n\n" : ANSI_COLOR_RED"Failed"ANSI_COLOR_RESET"\n\n");
```

2024-09-10 10:09 UTC, Dakshita-Minocha commented on Training/Training/main.c
> +         if (temp == binexpected[i][j])
```suggestion
         if (temp == binexpected[i][j]) flag++;
```

2024-09-10 10:09 UTC, closed without merging